# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75ce809c80739d805758801b557155dc5468dc07a12cd377b19b46d528c6c3fdc079550c89aa98d2e6e8be746a63c2bf7b42c6e383135638fbb5e3987d0d6f67

test:
  secret_key_base: 68ee5f8ec74653057dbf5cd2b7b62316415b1eb91ad566c20e5acc5875b3e2d5034e5b32eb489cfb42182684999c8cd3ce54e1eff0ea7bbb44e01bea25ab19f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
